#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Smartwatch_IoTFakeSensor")]
public partial class connectStore_linqDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAccount(Account instance);
  partial void UpdateAccount(Account instance);
  partial void DeleteAccount(Account instance);
  partial void InsertUser(User instance);
  partial void UpdateUser(User instance);
  partial void DeleteUser(User instance);
  partial void InsertDepartment(Department instance);
  partial void UpdateDepartment(Department instance);
  partial void DeleteDepartment(Department instance);
  partial void InsertItem(Item instance);
  partial void UpdateItem(Item instance);
  partial void DeleteItem(Item instance);
  partial void InsertSale(Sale instance);
  partial void UpdateSale(Sale instance);
  partial void DeleteSale(Sale instance);
  #endregion
	
	public connectStore_linqDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Smartwatch_IoTFakeSensorConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public connectStore_linqDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public connectStore_linqDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public connectStore_linqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public connectStore_linqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Account> Accounts
	{
		get
		{
			return this.GetTable<Account>();
		}
	}
	
	public System.Data.Linq.Table<User> Users
	{
		get
		{
			return this.GetTable<User>();
		}
	}
	
	public System.Data.Linq.Table<Department> Departments
	{
		get
		{
			return this.GetTable<Department>();
		}
	}
	
	public System.Data.Linq.Table<GP> GPs
	{
		get
		{
			return this.GetTable<GP>();
		}
	}
	
	public System.Data.Linq.Table<Heartrate> Heartrates
	{
		get
		{
			return this.GetTable<Heartrate>();
		}
	}
	
	public System.Data.Linq.Table<Item> Items
	{
		get
		{
			return this.GetTable<Item>();
		}
	}
	
	public System.Data.Linq.Table<Sale> Sales
	{
		get
		{
			return this.GetTable<Sale>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buyPacket")]
	public int buyPacket([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> account_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> packet_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> start_date)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_id, packet_id, start_date);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkIsPremium")]
	public int checkIsPremium([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> accountid)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountid);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkPacketInCart")]
	public ISingleResult<checkPacketInCartResult> checkPacketInCart([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> itemid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> account)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), itemid, account);
		return ((ISingleResult<checkPacketInCartResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.upDatePacket")]
	public int upDatePacket([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> saleid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> item_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> accountid)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saleid, item_id, accountid);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.COUNTofHR")]
	public ISingleResult<COUNTofHRResult> COUNTofHR([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> startdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> enddate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, startdate, enddate);
		return ((ISingleResult<COUNTofHRResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountOfvelocityGPS")]
	public ISingleResult<CountOfvelocityGPSResult> CountOfvelocityGPS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> startdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> enddate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, startdate, enddate);
		return ((ISingleResult<CountOfvelocityGPSResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getName")]
	public ISingleResult<getNameResult> getName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> accountid)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountid);
		return ((ISingleResult<getNameResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[getUserlever ]")]
	public ISingleResult<getUserlever_Result> getUserlever_([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> accountid)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountid);
		return ((ISingleResult<getUserlever_Result>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.INSERT_department")]
	public int INSERT_department([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string dept_name)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dept_name);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.INSERT_heartrate")]
	public int INSERT_heartrate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> heartrate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> time)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id, heartrate, date, time);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.INSERT_velocityGPS")]
	public int INSERT_velocityGPS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> velocity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> time)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id, velocity, date, time);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertItemsToSale")]
	public int insertItemsToSale([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> itemsid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> paid)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, itemsid, amount, paid);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertPacketToSaleorCart")]
	public int insertPacketToSaleorCart([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> itemid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string itemname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> paid)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), itemid, itemname, amount, price, userid, paid);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.isAdmin")]
	public ISingleResult<isAdminResult> isAdmin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> account_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_id);
		return ((ISingleResult<isAdminResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Register")]
	public int Register([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> account_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string account_username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string account_password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> account_userlevel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> account_packetid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> account_startpacket, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> account_enddatepacket, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string user_firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string user_lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_deptid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_salary, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_age)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_id, account_username, account_password, account_userlevel, account_packetid, account_startpacket, account_enddatepacket, user_id, user_firstname, user_lastname, user_deptid, user_address, user_salary, user_age);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.showAllHeatrateByID")]
	public ISingleResult<showAllHeatrateByIDResult> showAllHeatrateByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> account_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sortBy)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_id, sortBy);
		return ((ISingleResult<showAllHeatrateByIDResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.showHRBetweenDate")]
	public ISingleResult<showHRBetweenDateResult> showHRBetweenDate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> startdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> enddate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, startdate, enddate);
		return ((ISingleResult<showHRBetweenDateResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.showOrder")]
	public ISingleResult<showOrderResult> showOrder([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
		return ((ISingleResult<showOrderResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.showSaleSortByPaid")]
	public ISingleResult<showSaleSortByPaidResult> showSaleSortByPaid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> account_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isPaid_1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isPaid_2)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_id, isPaid_1, isPaid_2);
		return ((ISingleResult<showSaleSortByPaidResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.showSaleSortByPaidAdmin")]
	public ISingleResult<showSaleSortByPaidAdminResult> showSaleSortByPaidAdmin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isPaid_1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isPaid_2)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isPaid_1, isPaid_2);
		return ((ISingleResult<showSaleSortByPaidAdminResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.showSaleSortByPaidClient")]
	public ISingleResult<showSaleSortByPaidClientResult> showSaleSortByPaidClient([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> account_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isPaid_1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isPaid_2)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_id, isPaid_1, isPaid_2);
		return ((ISingleResult<showSaleSortByPaidClientResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.showvelocityBetweenDate")]
	public ISingleResult<showvelocityBetweenDateResult> showvelocityBetweenDate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> startdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> enddate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, startdate, enddate);
		return ((ISingleResult<showvelocityBetweenDateResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SUMofHR")]
	public ISingleResult<SUMofHRResult> SUMofHR([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> startdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> enddate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, startdate, enddate);
		return ((ISingleResult<SUMofHRResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SUMofvelocityGPS")]
	public ISingleResult<SUMofvelocityGPSResult> SUMofvelocityGPS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> startdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> enddate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, startdate, enddate);
		return ((ISingleResult<SUMofvelocityGPSResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.showPremiumUserOrFreeuser")]
	public ISingleResult<showPremiumUserOrFreeuserResult> showPremiumUserOrFreeuser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isPremium)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isPremium);
		return ((ISingleResult<showPremiumUserOrFreeuserResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.showAllincome")]
	public ISingleResult<showAllincomeResult> showAllincome()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<showAllincomeResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.showAllincomeI1")]
	public ISingleResult<showAllincomeI1Result> showAllincomeI1()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<showAllincomeI1Result>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.alertLessThan7Days")]
	public ISingleResult<alertLessThan7DaysResult> alertLessThan7Days([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accountid", DbType="Int")] System.Nullable<int> accountid)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountid);
		return ((ISingleResult<alertLessThan7DaysResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getBathOfPacket")]
	public ISingleResult<getBathOfPacketResult> getBathOfPacket()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<getBathOfPacketResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _accountid;
	
	private string _username;
	
	private string _password;
	
	private System.Nullable<int> _userlevel;
	
	private int _packetid;
	
	private System.DateTime _startpacket;
	
	private System.Nullable<System.DateTime> _enddatepacket;
	
	private EntityRef<User> _User;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnaccountidChanging(int value);
    partial void OnaccountidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnuserlevelChanging(System.Nullable<int> value);
    partial void OnuserlevelChanged();
    partial void OnpacketidChanging(int value);
    partial void OnpacketidChanged();
    partial void OnstartpacketChanging(System.DateTime value);
    partial void OnstartpacketChanged();
    partial void OnenddatepacketChanging(System.Nullable<System.DateTime> value);
    partial void OnenddatepacketChanged();
    #endregion
	
	public Account()
	{
		this._User = default(EntityRef<User>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accountid", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int accountid
	{
		get
		{
			return this._accountid;
		}
		set
		{
			if ((this._accountid != value))
			{
				if (this._User.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnaccountidChanging(value);
				this.SendPropertyChanging();
				this._accountid = value;
				this.SendPropertyChanged("accountid");
				this.OnaccountidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(20)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userlevel", DbType="Int")]
	public System.Nullable<int> userlevel
	{
		get
		{
			return this._userlevel;
		}
		set
		{
			if ((this._userlevel != value))
			{
				this.OnuserlevelChanging(value);
				this.SendPropertyChanging();
				this._userlevel = value;
				this.SendPropertyChanged("userlevel");
				this.OnuserlevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_packetid", DbType="Int NOT NULL")]
	public int packetid
	{
		get
		{
			return this._packetid;
		}
		set
		{
			if ((this._packetid != value))
			{
				this.OnpacketidChanging(value);
				this.SendPropertyChanging();
				this._packetid = value;
				this.SendPropertyChanged("packetid");
				this.OnpacketidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startpacket", DbType="Date NOT NULL")]
	public System.DateTime startpacket
	{
		get
		{
			return this._startpacket;
		}
		set
		{
			if ((this._startpacket != value))
			{
				this.OnstartpacketChanging(value);
				this.SendPropertyChanging();
				this._startpacket = value;
				this.SendPropertyChanged("startpacket");
				this.OnstartpacketChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enddatepacket", DbType="Date")]
	public System.Nullable<System.DateTime> enddatepacket
	{
		get
		{
			return this._enddatepacket;
		}
		set
		{
			if ((this._enddatepacket != value))
			{
				this.OnenddatepacketChanging(value);
				this.SendPropertyChanging();
				this._enddatepacket = value;
				this.SendPropertyChanged("enddatepacket");
				this.OnenddatepacketChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Account", Storage="_User", ThisKey="accountid", OtherKey="userid", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public User User
	{
		get
		{
			return this._User.Entity;
		}
		set
		{
			User previousValue = this._User.Entity;
			if (((previousValue != value) 
						|| (this._User.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._User.Entity = null;
					previousValue.Account = null;
				}
				this._User.Entity = value;
				if ((value != null))
				{
					value.Account = this;
					this._accountid = value.userid;
				}
				else
				{
					this._accountid = default(int);
				}
				this.SendPropertyChanged("User");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _userid;
	
	private string _firstname;
	
	private string _lastname;
	
	private System.Nullable<int> _dept_id;
	
	private string _address;
	
	private System.Nullable<int> _salary;
	
	private System.Nullable<int> _age;
	
	private EntityRef<Account> _Account;
	
	private EntitySet<Sale> _Sales;
	
	private EntityRef<Department> _Department;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void Ondept_idChanging(System.Nullable<int> value);
    partial void Ondept_idChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnsalaryChanging(System.Nullable<int> value);
    partial void OnsalaryChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    #endregion
	
	public User()
	{
		this._Account = default(EntityRef<Account>);
		this._Sales = new EntitySet<Sale>(new Action<Sale>(this.attach_Sales), new Action<Sale>(this.detach_Sales));
		this._Department = default(EntityRef<Department>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this.OnuseridChanging(value);
				this.SendPropertyChanging();
				this._userid = value;
				this.SendPropertyChanged("userid");
				this.OnuseridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(20)")]
	public string firstname
	{
		get
		{
			return this._firstname;
		}
		set
		{
			if ((this._firstname != value))
			{
				this.OnfirstnameChanging(value);
				this.SendPropertyChanging();
				this._firstname = value;
				this.SendPropertyChanged("firstname");
				this.OnfirstnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="NVarChar(20)")]
	public string lastname
	{
		get
		{
			return this._lastname;
		}
		set
		{
			if ((this._lastname != value))
			{
				this.OnlastnameChanging(value);
				this.SendPropertyChanging();
				this._lastname = value;
				this.SendPropertyChanged("lastname");
				this.OnlastnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_id", DbType="Int")]
	public System.Nullable<int> dept_id
	{
		get
		{
			return this._dept_id;
		}
		set
		{
			if ((this._dept_id != value))
			{
				if (this._Department.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ondept_idChanging(value);
				this.SendPropertyChanging();
				this._dept_id = value;
				this.SendPropertyChanged("dept_id");
				this.Ondept_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="Int")]
	public System.Nullable<int> salary
	{
		get
		{
			return this._salary;
		}
		set
		{
			if ((this._salary != value))
			{
				this.OnsalaryChanging(value);
				this.SendPropertyChanging();
				this._salary = value;
				this.SendPropertyChanged("salary");
				this.OnsalaryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
	public System.Nullable<int> age
	{
		get
		{
			return this._age;
		}
		set
		{
			if ((this._age != value))
			{
				this.OnageChanging(value);
				this.SendPropertyChanging();
				this._age = value;
				this.SendPropertyChanged("age");
				this.OnageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Account", Storage="_Account", ThisKey="userid", OtherKey="accountid", IsUnique=true, IsForeignKey=false)]
	public Account Account
	{
		get
		{
			return this._Account.Entity;
		}
		set
		{
			Account previousValue = this._Account.Entity;
			if (((previousValue != value) 
						|| (this._Account.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Account.Entity = null;
					previousValue.User = null;
				}
				this._Account.Entity = value;
				if ((value != null))
				{
					value.User = this;
				}
				this.SendPropertyChanged("Account");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Sale", Storage="_Sales", ThisKey="userid", OtherKey="userid")]
	public EntitySet<Sale> Sales
	{
		get
		{
			return this._Sales;
		}
		set
		{
			this._Sales.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Department_User", Storage="_Department", ThisKey="dept_id", OtherKey="dept_id", IsForeignKey=true, DeleteRule="CASCADE")]
	public Department Department
	{
		get
		{
			return this._Department.Entity;
		}
		set
		{
			Department previousValue = this._Department.Entity;
			if (((previousValue != value) 
						|| (this._Department.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Department.Entity = null;
					previousValue.Users.Remove(this);
				}
				this._Department.Entity = value;
				if ((value != null))
				{
					value.Users.Add(this);
					this._dept_id = value.dept_id;
				}
				else
				{
					this._dept_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("Department");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Sales(Sale entity)
	{
		this.SendPropertyChanging();
		entity.User = this;
	}
	
	private void detach_Sales(Sale entity)
	{
		this.SendPropertyChanging();
		entity.User = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Department")]
public partial class Department : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _dept_id;
	
	private string _deptname;
	
	private EntitySet<User> _Users;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondept_idChanging(int value);
    partial void Ondept_idChanged();
    partial void OndeptnameChanging(string value);
    partial void OndeptnameChanged();
    #endregion
	
	public Department()
	{
		this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int dept_id
	{
		get
		{
			return this._dept_id;
		}
		set
		{
			if ((this._dept_id != value))
			{
				this.Ondept_idChanging(value);
				this.SendPropertyChanging();
				this._dept_id = value;
				this.SendPropertyChanged("dept_id");
				this.Ondept_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptname", DbType="NVarChar(20)")]
	public string deptname
	{
		get
		{
			return this._deptname;
		}
		set
		{
			if ((this._deptname != value))
			{
				this.OndeptnameChanging(value);
				this.SendPropertyChanging();
				this._deptname = value;
				this.SendPropertyChanged("deptname");
				this.OndeptnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Department_User", Storage="_Users", ThisKey="dept_id", OtherKey="dept_id")]
	public EntitySet<User> Users
	{
		get
		{
			return this._Users;
		}
		set
		{
			this._Users.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Users(User entity)
	{
		this.SendPropertyChanging();
		entity.Department = this;
	}
	
	private void detach_Users(User entity)
	{
		this.SendPropertyChanging();
		entity.Department = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GPS")]
public partial class GP
{
	
	private System.Nullable<int> _userid;
	
	private System.Nullable<int> _gps;
	
	private System.Nullable<System.DateTime> _daterecord;
	
	private System.Nullable<System.TimeSpan> _time;
	
	public GP()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gps", DbType="Int")]
	public System.Nullable<int> gps
	{
		get
		{
			return this._gps;
		}
		set
		{
			if ((this._gps != value))
			{
				this._gps = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daterecord", DbType="Date")]
	public System.Nullable<System.DateTime> daterecord
	{
		get
		{
			return this._daterecord;
		}
		set
		{
			if ((this._daterecord != value))
			{
				this._daterecord = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time")]
	public System.Nullable<System.TimeSpan> time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this._time = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Heartrate")]
public partial class Heartrate
{
	
	private System.Nullable<int> _userid;
	
	private System.Nullable<double> _hr;
	
	private System.Nullable<System.DateTime> _daterecord;
	
	private System.Nullable<System.TimeSpan> _time;
	
	public Heartrate()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr", DbType="Float")]
	public System.Nullable<double> hr
	{
		get
		{
			return this._hr;
		}
		set
		{
			if ((this._hr != value))
			{
				this._hr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daterecord", DbType="Date")]
	public System.Nullable<System.DateTime> daterecord
	{
		get
		{
			return this._daterecord;
		}
		set
		{
			if ((this._daterecord != value))
			{
				this._daterecord = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time")]
	public System.Nullable<System.TimeSpan> time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this._time = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item")]
public partial class Item : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _itemid;
	
	private string _itemname;
	
	private System.Nullable<double> _price;
	
	private System.Nullable<int> _amount;
	
	private EntitySet<Sale> _Sales;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnitemidChanging(int value);
    partial void OnitemidChanged();
    partial void OnitemnameChanging(string value);
    partial void OnitemnameChanged();
    partial void OnpriceChanging(System.Nullable<double> value);
    partial void OnpriceChanged();
    partial void OnamountChanging(System.Nullable<int> value);
    partial void OnamountChanged();
    #endregion
	
	public Item()
	{
		this._Sales = new EntitySet<Sale>(new Action<Sale>(this.attach_Sales), new Action<Sale>(this.detach_Sales));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemid", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int itemid
	{
		get
		{
			return this._itemid;
		}
		set
		{
			if ((this._itemid != value))
			{
				this.OnitemidChanging(value);
				this.SendPropertyChanging();
				this._itemid = value;
				this.SendPropertyChanged("itemid");
				this.OnitemidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemname", DbType="NVarChar(20)")]
	public string itemname
	{
		get
		{
			return this._itemname;
		}
		set
		{
			if ((this._itemname != value))
			{
				this.OnitemnameChanging(value);
				this.SendPropertyChanging();
				this._itemname = value;
				this.SendPropertyChanged("itemname");
				this.OnitemnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
	public System.Nullable<double> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Int")]
	public System.Nullable<int> amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this.OnamountChanging(value);
				this.SendPropertyChanging();
				this._amount = value;
				this.SendPropertyChanged("amount");
				this.OnamountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Sale", Storage="_Sales", ThisKey="itemid", OtherKey="itemid")]
	public EntitySet<Sale> Sales
	{
		get
		{
			return this._Sales;
		}
		set
		{
			this._Sales.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Sales(Sale entity)
	{
		this.SendPropertyChanging();
		entity.Item = this;
	}
	
	private void detach_Sales(Sale entity)
	{
		this.SendPropertyChanging();
		entity.Item = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sale")]
public partial class Sale : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _saleid;
	
	private System.Nullable<int> _itemid;
	
	private string _itemname;
	
	private System.Nullable<int> _amount;
	
	private System.Nullable<int> _price;
	
	private System.Nullable<int> _userid;
	
	private System.Nullable<int> _paid;
	
	private EntityRef<Item> _Item;
	
	private EntityRef<User> _User;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsaleidChanging(int value);
    partial void OnsaleidChanged();
    partial void OnitemidChanging(System.Nullable<int> value);
    partial void OnitemidChanged();
    partial void OnitemnameChanging(string value);
    partial void OnitemnameChanged();
    partial void OnamountChanging(System.Nullable<int> value);
    partial void OnamountChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OnuseridChanging(System.Nullable<int> value);
    partial void OnuseridChanged();
    partial void OnpaidChanging(System.Nullable<int> value);
    partial void OnpaidChanged();
    #endregion
	
	public Sale()
	{
		this._Item = default(EntityRef<Item>);
		this._User = default(EntityRef<User>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saleid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int saleid
	{
		get
		{
			return this._saleid;
		}
		set
		{
			if ((this._saleid != value))
			{
				this.OnsaleidChanging(value);
				this.SendPropertyChanging();
				this._saleid = value;
				this.SendPropertyChanged("saleid");
				this.OnsaleidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemid", DbType="Int")]
	public System.Nullable<int> itemid
	{
		get
		{
			return this._itemid;
		}
		set
		{
			if ((this._itemid != value))
			{
				if (this._Item.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnitemidChanging(value);
				this.SendPropertyChanging();
				this._itemid = value;
				this.SendPropertyChanged("itemid");
				this.OnitemidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemname", DbType="VarChar(50)")]
	public string itemname
	{
		get
		{
			return this._itemname;
		}
		set
		{
			if ((this._itemname != value))
			{
				this.OnitemnameChanging(value);
				this.SendPropertyChanging();
				this._itemname = value;
				this.SendPropertyChanged("itemname");
				this.OnitemnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Int")]
	public System.Nullable<int> amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this.OnamountChanging(value);
				this.SendPropertyChanging();
				this._amount = value;
				this.SendPropertyChanged("amount");
				this.OnamountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
	public System.Nullable<int> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				if (this._User.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnuseridChanging(value);
				this.SendPropertyChanging();
				this._userid = value;
				this.SendPropertyChanged("userid");
				this.OnuseridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid", DbType="Int")]
	public System.Nullable<int> paid
	{
		get
		{
			return this._paid;
		}
		set
		{
			if ((this._paid != value))
			{
				this.OnpaidChanging(value);
				this.SendPropertyChanging();
				this._paid = value;
				this.SendPropertyChanged("paid");
				this.OnpaidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Sale", Storage="_Item", ThisKey="itemid", OtherKey="itemid", IsForeignKey=true, DeleteRule="CASCADE")]
	public Item Item
	{
		get
		{
			return this._Item.Entity;
		}
		set
		{
			Item previousValue = this._Item.Entity;
			if (((previousValue != value) 
						|| (this._Item.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Item.Entity = null;
					previousValue.Sales.Remove(this);
				}
				this._Item.Entity = value;
				if ((value != null))
				{
					value.Sales.Add(this);
					this._itemid = value.itemid;
				}
				else
				{
					this._itemid = default(Nullable<int>);
				}
				this.SendPropertyChanged("Item");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Sale", Storage="_User", ThisKey="userid", OtherKey="userid", IsForeignKey=true)]
	public User User
	{
		get
		{
			return this._User.Entity;
		}
		set
		{
			User previousValue = this._User.Entity;
			if (((previousValue != value) 
						|| (this._User.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._User.Entity = null;
					previousValue.Sales.Remove(this);
				}
				this._User.Entity = value;
				if ((value != null))
				{
					value.Sales.Add(this);
					this._userid = value.userid;
				}
				else
				{
					this._userid = default(Nullable<int>);
				}
				this.SendPropertyChanged("User");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class checkPacketInCartResult
{
	
	private int _saleid;
	
	private System.Nullable<int> _itemid;
	
	private string _itemname;
	
	private System.Nullable<int> _amount;
	
	private System.Nullable<int> _price;
	
	private System.Nullable<int> _userid;
	
	private System.Nullable<int> _paid;
	
	public checkPacketInCartResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saleid", DbType="Int NOT NULL")]
	public int saleid
	{
		get
		{
			return this._saleid;
		}
		set
		{
			if ((this._saleid != value))
			{
				this._saleid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemid", DbType="Int")]
	public System.Nullable<int> itemid
	{
		get
		{
			return this._itemid;
		}
		set
		{
			if ((this._itemid != value))
			{
				this._itemid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemname", DbType="VarChar(50)")]
	public string itemname
	{
		get
		{
			return this._itemname;
		}
		set
		{
			if ((this._itemname != value))
			{
				this._itemname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Int")]
	public System.Nullable<int> amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this._amount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
	public System.Nullable<int> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid", DbType="Int")]
	public System.Nullable<int> paid
	{
		get
		{
			return this._paid;
		}
		set
		{
			if ((this._paid != value))
			{
				this._paid = value;
			}
		}
	}
}

public partial class COUNTofHRResult
{
	
	private System.Nullable<int> _Column1;
	
	public COUNTofHRResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
	public System.Nullable<int> Column1
	{
		get
		{
			return this._Column1;
		}
		set
		{
			if ((this._Column1 != value))
			{
				this._Column1 = value;
			}
		}
	}
}

public partial class CountOfvelocityGPSResult
{
	
	private System.Nullable<int> _Column1;
	
	public CountOfvelocityGPSResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
	public System.Nullable<int> Column1
	{
		get
		{
			return this._Column1;
		}
		set
		{
			if ((this._Column1 != value))
			{
				this._Column1 = value;
			}
		}
	}
}

public partial class getNameResult
{
	
	private string _firstname;
	
	public getNameResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(20)")]
	public string firstname
	{
		get
		{
			return this._firstname;
		}
		set
		{
			if ((this._firstname != value))
			{
				this._firstname = value;
			}
		}
	}
}

public partial class getUserlever_Result
{
	
	private System.Nullable<int> _userlevel;
	
	public getUserlever_Result()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userlevel", DbType="Int")]
	public System.Nullable<int> userlevel
	{
		get
		{
			return this._userlevel;
		}
		set
		{
			if ((this._userlevel != value))
			{
				this._userlevel = value;
			}
		}
	}
}

public partial class isAdminResult
{
	
	private System.Nullable<int> _dept_id;
	
	public isAdminResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_id", DbType="Int")]
	public System.Nullable<int> dept_id
	{
		get
		{
			return this._dept_id;
		}
		set
		{
			if ((this._dept_id != value))
			{
				this._dept_id = value;
			}
		}
	}
}

public partial class showAllHeatrateByIDResult
{
	
	private System.Nullable<int> _userid;
	
	private System.Nullable<double> _hr;
	
	private System.Nullable<System.DateTime> _daterecord;
	
	private System.Nullable<System.TimeSpan> _time;
	
	public showAllHeatrateByIDResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr", DbType="Float")]
	public System.Nullable<double> hr
	{
		get
		{
			return this._hr;
		}
		set
		{
			if ((this._hr != value))
			{
				this._hr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daterecord", DbType="Date")]
	public System.Nullable<System.DateTime> daterecord
	{
		get
		{
			return this._daterecord;
		}
		set
		{
			if ((this._daterecord != value))
			{
				this._daterecord = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time")]
	public System.Nullable<System.TimeSpan> time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this._time = value;
			}
		}
	}
}

public partial class showHRBetweenDateResult
{
	
	private System.Nullable<int> _userid;
	
	private System.Nullable<double> _hr;
	
	private System.Nullable<System.DateTime> _daterecord;
	
	private System.Nullable<System.TimeSpan> _time;
	
	public showHRBetweenDateResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr", DbType="Float")]
	public System.Nullable<double> hr
	{
		get
		{
			return this._hr;
		}
		set
		{
			if ((this._hr != value))
			{
				this._hr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daterecord", DbType="Date")]
	public System.Nullable<System.DateTime> daterecord
	{
		get
		{
			return this._daterecord;
		}
		set
		{
			if ((this._daterecord != value))
			{
				this._daterecord = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time")]
	public System.Nullable<System.TimeSpan> time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this._time = value;
			}
		}
	}
}

public partial class showOrderResult
{
	
	private int _saleid;
	
	private System.Nullable<int> _itemid;
	
	private string _itemname;
	
	private System.Nullable<int> _amount;
	
	private System.Nullable<int> _price;
	
	private System.Nullable<int> _userid;
	
	private System.Nullable<int> _paid;
	
	public showOrderResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saleid", DbType="Int NOT NULL")]
	public int saleid
	{
		get
		{
			return this._saleid;
		}
		set
		{
			if ((this._saleid != value))
			{
				this._saleid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemid", DbType="Int")]
	public System.Nullable<int> itemid
	{
		get
		{
			return this._itemid;
		}
		set
		{
			if ((this._itemid != value))
			{
				this._itemid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemname", DbType="VarChar(50)")]
	public string itemname
	{
		get
		{
			return this._itemname;
		}
		set
		{
			if ((this._itemname != value))
			{
				this._itemname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Int")]
	public System.Nullable<int> amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this._amount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
	public System.Nullable<int> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid", DbType="Int")]
	public System.Nullable<int> paid
	{
		get
		{
			return this._paid;
		}
		set
		{
			if ((this._paid != value))
			{
				this._paid = value;
			}
		}
	}
}

public partial class showSaleSortByPaidResult
{
	
	private int _saleid;
	
	private System.Nullable<int> _itemid;
	
	private string _itemname;
	
	private System.Nullable<int> _amount;
	
	private System.Nullable<int> _price;
	
	private System.Nullable<int> _userid;
	
	private System.Nullable<int> _paid;
	
	public showSaleSortByPaidResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saleid", DbType="Int NOT NULL")]
	public int saleid
	{
		get
		{
			return this._saleid;
		}
		set
		{
			if ((this._saleid != value))
			{
				this._saleid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemid", DbType="Int")]
	public System.Nullable<int> itemid
	{
		get
		{
			return this._itemid;
		}
		set
		{
			if ((this._itemid != value))
			{
				this._itemid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemname", DbType="VarChar(50)")]
	public string itemname
	{
		get
		{
			return this._itemname;
		}
		set
		{
			if ((this._itemname != value))
			{
				this._itemname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Int")]
	public System.Nullable<int> amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this._amount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
	public System.Nullable<int> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid", DbType="Int")]
	public System.Nullable<int> paid
	{
		get
		{
			return this._paid;
		}
		set
		{
			if ((this._paid != value))
			{
				this._paid = value;
			}
		}
	}
}

public partial class showSaleSortByPaidAdminResult
{
	
	private int _saleid;
	
	private System.Nullable<int> _itemid;
	
	private string _itemname;
	
	private System.Nullable<int> _amount;
	
	private System.Nullable<int> _price;
	
	private System.Nullable<int> _userid;
	
	private System.Nullable<int> _paid;
	
	public showSaleSortByPaidAdminResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saleid", DbType="Int NOT NULL")]
	public int saleid
	{
		get
		{
			return this._saleid;
		}
		set
		{
			if ((this._saleid != value))
			{
				this._saleid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemid", DbType="Int")]
	public System.Nullable<int> itemid
	{
		get
		{
			return this._itemid;
		}
		set
		{
			if ((this._itemid != value))
			{
				this._itemid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemname", DbType="VarChar(50)")]
	public string itemname
	{
		get
		{
			return this._itemname;
		}
		set
		{
			if ((this._itemname != value))
			{
				this._itemname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Int")]
	public System.Nullable<int> amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this._amount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
	public System.Nullable<int> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid", DbType="Int")]
	public System.Nullable<int> paid
	{
		get
		{
			return this._paid;
		}
		set
		{
			if ((this._paid != value))
			{
				this._paid = value;
			}
		}
	}
}

public partial class showSaleSortByPaidClientResult
{
	
	private int _saleid;
	
	private System.Nullable<int> _itemid;
	
	private string _itemname;
	
	private System.Nullable<int> _amount;
	
	private System.Nullable<int> _price;
	
	private System.Nullable<int> _userid;
	
	private System.Nullable<int> _paid;
	
	public showSaleSortByPaidClientResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saleid", DbType="Int NOT NULL")]
	public int saleid
	{
		get
		{
			return this._saleid;
		}
		set
		{
			if ((this._saleid != value))
			{
				this._saleid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemid", DbType="Int")]
	public System.Nullable<int> itemid
	{
		get
		{
			return this._itemid;
		}
		set
		{
			if ((this._itemid != value))
			{
				this._itemid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemname", DbType="VarChar(50)")]
	public string itemname
	{
		get
		{
			return this._itemname;
		}
		set
		{
			if ((this._itemname != value))
			{
				this._itemname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Int")]
	public System.Nullable<int> amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this._amount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
	public System.Nullable<int> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid", DbType="Int")]
	public System.Nullable<int> paid
	{
		get
		{
			return this._paid;
		}
		set
		{
			if ((this._paid != value))
			{
				this._paid = value;
			}
		}
	}
}

public partial class showvelocityBetweenDateResult
{
	
	private System.Nullable<int> _userid;
	
	private System.Nullable<int> _gps;
	
	private System.Nullable<System.DateTime> _daterecord;
	
	private System.Nullable<System.TimeSpan> _time;
	
	public showvelocityBetweenDateResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gps", DbType="Int")]
	public System.Nullable<int> gps
	{
		get
		{
			return this._gps;
		}
		set
		{
			if ((this._gps != value))
			{
				this._gps = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daterecord", DbType="Date")]
	public System.Nullable<System.DateTime> daterecord
	{
		get
		{
			return this._daterecord;
		}
		set
		{
			if ((this._daterecord != value))
			{
				this._daterecord = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time")]
	public System.Nullable<System.TimeSpan> time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this._time = value;
			}
		}
	}
}

public partial class SUMofHRResult
{
	
	private System.Nullable<double> _Column1;
	
	public SUMofHRResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Float")]
	public System.Nullable<double> Column1
	{
		get
		{
			return this._Column1;
		}
		set
		{
			if ((this._Column1 != value))
			{
				this._Column1 = value;
			}
		}
	}
}

public partial class SUMofvelocityGPSResult
{
	
	private System.Nullable<int> _Column1;
	
	public SUMofvelocityGPSResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
	public System.Nullable<int> Column1
	{
		get
		{
			return this._Column1;
		}
		set
		{
			if ((this._Column1 != value))
			{
				this._Column1 = value;
			}
		}
	}
}

public partial class showPremiumUserOrFreeuserResult
{
	
	private System.Nullable<int> _userid;
	
	private string _firstname;
	
	private string _lastname;
	
	private System.Nullable<int> _packetid;
	
	private System.Nullable<System.DateTime> _startpacket;
	
	private System.Nullable<System.DateTime> _enddatepacket;
	
	public showPremiumUserOrFreeuserResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
	public System.Nullable<int> userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this._userid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(20)")]
	public string firstname
	{
		get
		{
			return this._firstname;
		}
		set
		{
			if ((this._firstname != value))
			{
				this._firstname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="NVarChar(20)")]
	public string lastname
	{
		get
		{
			return this._lastname;
		}
		set
		{
			if ((this._lastname != value))
			{
				this._lastname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_packetid", DbType="Int")]
	public System.Nullable<int> packetid
	{
		get
		{
			return this._packetid;
		}
		set
		{
			if ((this._packetid != value))
			{
				this._packetid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startpacket", DbType="Date")]
	public System.Nullable<System.DateTime> startpacket
	{
		get
		{
			return this._startpacket;
		}
		set
		{
			if ((this._startpacket != value))
			{
				this._startpacket = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enddatepacket", DbType="Date")]
	public System.Nullable<System.DateTime> enddatepacket
	{
		get
		{
			return this._enddatepacket;
		}
		set
		{
			if ((this._enddatepacket != value))
			{
				this._enddatepacket = value;
			}
		}
	}
}

public partial class showAllincomeResult
{
	
	private System.Nullable<int> _Column1;
	
	public showAllincomeResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
	public System.Nullable<int> Column1
	{
		get
		{
			return this._Column1;
		}
		set
		{
			if ((this._Column1 != value))
			{
				this._Column1 = value;
			}
		}
	}
}

public partial class showAllincomeI1Result
{
	
	private System.Nullable<int> _Column1;
	
	public showAllincomeI1Result()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
	public System.Nullable<int> Column1
	{
		get
		{
			return this._Column1;
		}
		set
		{
			if ((this._Column1 != value))
			{
				this._Column1 = value;
			}
		}
	}
}

public partial class alertLessThan7DaysResult
{
	
	private int _accountid;
	
	public alertLessThan7DaysResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accountid", DbType="Int NOT NULL")]
	public int accountid
	{
		get
		{
			return this._accountid;
		}
		set
		{
			if ((this._accountid != value))
			{
				this._accountid = value;
			}
		}
	}
}

public partial class getBathOfPacketResult
{
	
	private System.Nullable<double> _price;
	
	public getBathOfPacketResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
	public System.Nullable<double> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
}
#pragma warning restore 1591
